package com.mdframe.forge.plugin.generator.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mdframe.forge.plugin.generator.domain.entity.AiCrudConfig;
import com.mdframe.forge.plugin.generator.dto.lowcode.LowcodePrimaryKeyStrategy;
import com.mdframe.forge.plugin.generator.service.audit.DataAuditPayloadSupport;
import com.mdframe.forge.plugin.generator.service.formula.StoredAggregateRefreshService;
import com.mdframe.forge.plugin.generator.service.lowcode.runtime.LowcodeRuntimeDataSourceContext;
import com.mdframe.forge.plugin.generator.service.lowcode.runtime.LowcodeRuntimeDataSourceContextHolder;
import com.mdframe.forge.plugin.generator.util.DynamicQueryGenerator;
import com.mdframe.forge.starter.core.exception.BusinessException;
import org.apache.commons.lang3.StringUtils;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;

/**
 * 动态 CRUD 写模型协调器。
 *
 * <p>采用 Command/Coordinator 模式集中普通表单、内部自动化和业务命令的写入管线，
 * 门面服务只负责事务、审计和运行时数据源边界。</p>
 */
final class DynamicCrudMutationCoordinator {

    private static final Set<String> IMMUTABLE_WRITE_FIELDS = Set.of(
            "id", "tenantId", "tenant_id", "createBy", "create_by", "createTime", "create_time",
            "createDept", "create_dept", "updateBy", "update_by", "updateTime", "update_time",
            "delFlag", "del_flag"
    );

    private final DynamicCrudRepository repository;
    private final ObjectMapper objectMapper;
    private final StoredAggregateRefreshService storedAggregateRefreshService;
    private final DynamicCrudUniquenessValidator uniquenessValidator;
    private final DynamicCrudGeneratedFieldPolicy generatedFieldPolicy;
    private final DynamicCrudFieldValuePipeline fieldValuePipeline;
    private final DynamicCrudWriteFieldPolicy writeFieldPolicy;
    private final DynamicCrudRuntimeRelationPlanner runtimeRelationPlanner;
    private final DynamicCrudMasterDetailEngine masterDetailEngine;
    private final DynamicCrudJoinedPersistenceEngine joinedPersistenceEngine;

    DynamicCrudMutationCoordinator(
            DynamicCrudRepository repository,
            ObjectMapper objectMapper,
            StoredAggregateRefreshService storedAggregateRefreshService,
            DynamicCrudUniquenessValidator uniquenessValidator,
            DynamicCrudGeneratedFieldPolicy generatedFieldPolicy,
            DynamicCrudFieldValuePipeline fieldValuePipeline,
            DynamicCrudWriteFieldPolicy writeFieldPolicy,
            DynamicCrudRuntimeRelationPlanner runtimeRelationPlanner,
            DynamicCrudMasterDetailEngine masterDetailEngine,
            DynamicCrudJoinedPersistenceEngine joinedPersistenceEngine) {
        this.repository = repository;
        this.objectMapper = objectMapper;
        this.storedAggregateRefreshService = storedAggregateRefreshService;
        this.uniquenessValidator = uniquenessValidator;
        this.generatedFieldPolicy = generatedFieldPolicy;
        this.fieldValuePipeline = fieldValuePipeline;
        this.writeFieldPolicy = writeFieldPolicy;
        this.runtimeRelationPlanner = runtimeRelationPlanner;
        this.masterDetailEngine = masterDetailEngine;
        this.joinedPersistenceEngine = joinedPersistenceEngine;
    }

    Map<String, Object> insertForm(AiCrudConfig config,
                                   Map<String, Object> data,
                                   Function<Object, Map<String, Object>> resultLoader) {
        String tableName = config.getTableName();
        Map<String, String> columnMapping = writeFieldPolicy.buildRuntimeColumnMapping(config, tableName);
        Set<String> allowedFields = writeFieldPolicy.buildAllowedWriteFields(config, tableName);
        generatedFieldPolicy.applyAutoGeneratedFields(config, data, allowedFields);
        generatedFieldPolicy.applyDocumentNoIfNeeded(config, data, allowedFields);
        SelectionIdentifierValidator.validate(config, data, objectMapper);

        RuntimeJoinContext joinContext = buildRuntimeJoinContext(config);
        if (runtimeRelationPlanner.isMasterDetailRuntime(config) && joinContext != null) {
            masterDetailEngine.insert(config, data, allowedFields, joinContext);
            return data;
        }
        if (joinContext != null) {
            joinedPersistenceEngine.insert(config, data, allowedFields, joinContext);
            return data;
        }

        writeFieldPolicy.applyStoredFormulas(config, data);
        writeFieldPolicy.validateFieldValues(config, data);
        Map<String, Object> filteredData = new LinkedHashMap<>();
        for (Map.Entry<String, Object> entry : data.entrySet()) {
            if (!isImmutableWriteField(entry.getKey()) && allowedFields.contains(entry.getKey())) {
                filteredData.put(columnMapping.getOrDefault(
                        entry.getKey(), DynamicQueryGenerator.camelToSnake(entry.getKey())), entry.getValue());
            }
        }
        if (filteredData.isEmpty()) {
            throw new BusinessException("没有可写入的字段");
        }

        validateUniqueConstraints(config, tableName, data, null, null);
        fieldValuePipeline.applyMoneyStorageWrite(filteredData, config);
        prepareStorageWrite(filteredData, config);
        return insertAndLoad(config, data, filteredData, resultLoader, true);
    }

    Map<String, Object> insertInternal(AiCrudConfig config,
                                       Map<String, Object> data,
                                       Function<Object, Map<String, Object>> resultLoader) {
        String tableName = config.getTableName();
        Set<String> allowedFields = writeFieldPolicy.collectInternalWriteFields(config, tableName);
        generatedFieldPolicy.applyAutoGeneratedFields(config, data, allowedFields);
        generatedFieldPolicy.applyDocumentNoIfNeeded(config, data, allowedFields);
        writeFieldPolicy.applyStoredFormulas(config, data);
        writeFieldPolicy.validateFieldValues(config, data);
        Map<String, Object> filteredData = writeFieldPolicy.filterInternalWriteData(config, tableName, data);
        if (filteredData.isEmpty()) {
            throw new BusinessException("没有可写入的字段");
        }
        validateUniqueConstraints(config, tableName, data, null, null);
        prepareStorageWrite(filteredData, config);
        return insertAndLoad(config, data, filteredData, resultLoader, false);
    }

    Map<String, Object> insertCommand(AiCrudConfig config,
                                      Map<String, Object> data,
                                      Function<Object, Map<String, Object>> resultLoader) {
        String tableName = config.getTableName();
        Set<String> allowedFields = writeFieldPolicy.collectCommandFields(config);
        generatedFieldPolicy.applyAutoGeneratedFields(config, data, allowedFields);
        generatedFieldPolicy.applyDocumentNoIfNeeded(config, data, allowedFields);
        writeFieldPolicy.applyStoredFormulas(config, data);
        writeFieldPolicy.validateFieldValues(config, data);
        Map<String, Object> filteredData = writeFieldPolicy.filterCommandWriteData(config, tableName, data);
        if (filteredData.isEmpty()) {
            throw new BusinessException("没有可写入的字段");
        }
        validateUniqueConstraints(config, tableName, data, null, null);
        prepareStorageWrite(filteredData, config);
        return insertAndLoad(config, data, filteredData, resultLoader, false);
    }

    void updateForm(AiCrudConfig config,
                    Object id,
                    Map<String, Object> data,
                    DynamicCrudRepository.SqlCondition dataScopeCondition) {
        String tableName = config.getTableName();
        LowcodePrimaryKeyStrategy primaryKey = currentPrimaryKey();
        Map<String, String> columnMapping = writeFieldPolicy.buildRuntimeColumnMapping(config, tableName);
        Set<String> allowedFields = writeFieldPolicy.buildAllowedWriteFields(config, tableName);
        SelectionIdentifierValidator.validate(config, data, objectMapper);

        RuntimeJoinContext joinContext = buildRuntimeJoinContext(config);
        if (runtimeRelationPlanner.isMasterDetailRuntime(config) && joinContext != null) {
            masterDetailEngine.update(config, id, data, allowedFields, joinContext, dataScopeCondition);
            return;
        }
        if (joinContext != null) {
            joinedPersistenceEngine.update(config, id, data, allowedFields, joinContext, dataScopeCondition);
            return;
        }

        Map<String, Object> beforeRecord = writeFieldPolicy.applyStoredFormulasForUpdate(
                config, tableName, id, data, dataScopeCondition);
        writeFieldPolicy.validateFieldValues(config, data);
        Map<String, Object> filteredData = new LinkedHashMap<>();
        for (Map.Entry<String, Object> entry : data.entrySet()) {
            String key = entry.getKey();
            if (isImmutableWriteField(key) || !allowedFields.contains(key)) {
                continue;
            }
            String columnName = columnMapping.getOrDefault(key, DynamicQueryGenerator.camelToSnake(key));
            if (!isPrimaryKeyAlias(key, columnName, primaryKey)) {
                filteredData.put(columnName, entry.getValue());
            }
        }
        fieldValuePipeline.removeMaskedDesensitizedWriteColumns(filteredData, config, columnMapping);
        if (filteredData.isEmpty()) {
            throw emptyWriteFieldsException(config, data.keySet(), allowedFields);
        }

        validateUniqueConstraints(config, tableName, data, beforeRecord, id);
        fieldValuePipeline.applyMoneyStorageWrite(filteredData, config);
        prepareStorageWrite(filteredData, config);
        updateAndRefresh(config, id, filteredData, dataScopeCondition, beforeRecord);
    }

    void updateRuntimeFields(AiCrudConfig config,
                             Object id,
                             Map<String, Object> data,
                             DynamicCrudRepository.SqlCondition dataScopeCondition) {
        String tableName = config.getTableName();
        LowcodePrimaryKeyStrategy primaryKey = currentPrimaryKey();
        Map<String, String> columnMapping = writeFieldPolicy.buildRuntimeColumnMapping(config, tableName);
        Set<String> tableColumns = repository.getTableColumns(tableName);
        Map<String, Object> beforeRecord = writeFieldPolicy.applyStoredFormulasForUpdate(
                config, tableName, id, data, dataScopeCondition);
        writeFieldPolicy.validateFieldValues(config, data);

        Map<String, Object> filteredData = new LinkedHashMap<>();
        for (Map.Entry<String, Object> entry : data.entrySet()) {
            String key = entry.getKey();
            if (isImmutableWriteField(key)) {
                continue;
            }
            String columnName = columnMapping.getOrDefault(key, DynamicQueryGenerator.camelToSnake(key));
            repository.validateIdentifier(columnName);
            if (!tableColumns.contains(columnName)) {
                throw writeFieldPolicy.missingRuntimeColumn(config, tableName, key, columnName);
            }
            if (!isImmutableWriteField(columnName) && !isPrimaryKeyAlias(key, columnName, primaryKey)) {
                filteredData.put(columnName, entry.getValue());
            }
        }
        if (filteredData.isEmpty()) {
            throw new BusinessException("没有可更新的字段");
        }
        prepareStorageWrite(filteredData, config);
        updateAndRefresh(config, id, filteredData, dataScopeCondition, beforeRecord);
    }

    void updateAutomationFields(AiCrudConfig config,
                                Object id,
                                Map<String, Object> fields,
                                DynamicCrudRepository.SqlCondition dataScopeCondition) {
        String tableName = config.getTableName();
        LowcodePrimaryKeyStrategy primaryKey = currentPrimaryKey();
        Map<String, Object> beforeRecord = writeFieldPolicy.applyStoredFormulasForUpdate(
                config, tableName, id, fields, dataScopeCondition);
        writeFieldPolicy.validateFieldValues(config, fields);
        Map<String, Object> filteredData = writeFieldPolicy.filterInternalWriteData(config, tableName, fields);
        if (filteredData.isEmpty()) {
            throw new BusinessException("没有可更新的字段");
        }
        prepareStorageWrite(filteredData, config);
        removePrimaryKeyColumns(filteredData, primaryKey);
        updateAndRefresh(config, id, filteredData, dataScopeCondition, beforeRecord);
    }

    void updateCommandFields(AiCrudConfig config,
                             Object id,
                             Map<String, Object> fields,
                             Map<String, Object> expectedFields,
                             DynamicCrudRepository.SqlCondition dataScope) {
        String tableName = config.getTableName();
        LowcodePrimaryKeyStrategy primaryKey = currentPrimaryKey();
        Map<String, Object> beforeRecord = writeFieldPolicy.applyStoredFormulasForUpdate(
                config, tableName, id, fields, dataScope);
        writeFieldPolicy.validateFieldValues(config, fields);
        Map<String, Object> filteredData = writeFieldPolicy.filterCommandWriteData(config, tableName, fields);
        if (filteredData.isEmpty()) {
            throw new BusinessException("没有可更新的字段");
        }
        prepareStorageWrite(filteredData, config);
        removePrimaryKeyColumns(filteredData, primaryKey);
        DynamicCrudRepository.SqlCondition expected = writeFieldPolicy.buildCommandExpectedCondition(
                config, tableName, expectedFields);
        updateAndRefresh(config, id, filteredData,
                writeFieldPolicy.combineConditions(dataScope, expected), beforeRecord,
                "记录已变化、数值越界或无权限更新");
    }

    void adjustCommandNumbers(AiCrudConfig config,
                              Object id,
                              Map<String, BigDecimal> deltas,
                              Map<String, BigDecimal> minimums,
                              Map<String, BigDecimal> maximums,
                              Map<String, Object> expectedFields,
                              DynamicCrudRepository.SqlCondition dataScope) {
        String tableName = config.getTableName();
        LowcodePrimaryKeyStrategy primaryKey = currentPrimaryKey();
        Map<String, BigDecimal> mappedDeltas = writeFieldPolicy.mapCommandDecimalFields(config, tableName, deltas);
        Map<String, BigDecimal> mappedMinimums = writeFieldPolicy.mapCommandDecimalFields(config, tableName, minimums);
        Map<String, BigDecimal> mappedMaximums = writeFieldPolicy.mapCommandDecimalFields(config, tableName, maximums);
        DynamicCrudRepository.SqlCondition expected = writeFieldPolicy.buildCommandExpectedCondition(
                config, tableName, expectedFields);
        Map<String, Object> before = repository.selectById(
                tableName, primaryKeyColumn(primaryKey), id, dataScope);
        if (before == null) {
            throw new BusinessException("记录不存在或无权限调整");
        }
        int affected = repository.adjustNumbersById(
                tableName, primaryKeyColumn(primaryKey), id,
                mappedDeltas, mappedMinimums, mappedMaximums,
                writeFieldPolicy.combineConditions(dataScope, expected));
        if (affected <= 0) {
            throw new BusinessException("记录已变化、数值越界或无权限调整");
        }
        refreshAfterUpdate(config, id, before);
    }

    void assertCommandRecord(AiCrudConfig config,
                             Object id,
                             Map<String, Object> expectedFields,
                             List<Map<String, Object>> numericConstraints,
                             DynamicCrudRepository.SqlCondition dataScope) {
        String tableName = config.getTableName();
        DynamicCrudRepository.SqlCondition expected = writeFieldPolicy.buildCommandExpectedCondition(
                config, tableName, expectedFields);
        DynamicCrudRepository.SqlCondition numeric = writeFieldPolicy.buildCommandNumericCondition(
                config, tableName, numericConstraints);
        Map<String, Object> record = repository.selectByIdForUpdate(
                tableName, primaryKeyColumn(currentPrimaryKey()), id,
                writeFieldPolicy.combineConditions(writeFieldPolicy.combineConditions(dataScope, expected), numeric));
        if (record == null) {
            throw new BusinessException("记录状态不满足门禁、无权限访问或记录不存在");
        }
    }

    Object resolvePayloadId(Map<String, Object> data) {
        return resolvePayloadId(data, currentPrimaryKey());
    }

    private Map<String, Object> insertAndLoad(AiCrudConfig config,
                                              Map<String, Object> data,
                                              Map<String, Object> filteredData,
                                              Function<Object, Map<String, Object>> resultLoader,
                                              boolean returnOriginalWhenKeyMissing) {
        LowcodePrimaryKeyStrategy primaryKey = currentPrimaryKey();
        Object id = repository.insertReturningKey(
                config.getTableName(), filteredData, primaryKeyColumn(primaryKey), primaryKeyAutoIncrement(primaryKey));
        if (id == null && returnOriginalWhenKeyMissing) {
            storedAggregateRefreshService.refreshAfterChildInsert(config, data);
            return data;
        }
        Map<String, Object> result = id == null ? null : resultLoader.apply(id);
        if (result != null) {
            storedAggregateRefreshService.refreshAfterChildInsert(config, result);
            return result;
        }
        Map<String, Object> fallback = new LinkedHashMap<>(data);
        putPrimaryKeyAlias(fallback, primaryKey, id);
        storedAggregateRefreshService.refreshAfterChildInsert(config, fallback);
        return fallback;
    }

    private void updateAndRefresh(AiCrudConfig config,
                                  Object id,
                                  Map<String, Object> data,
                                  DynamicCrudRepository.SqlCondition condition,
                                  Map<String, Object> beforeRecord) {
        updateAndRefresh(config, id, data, condition, beforeRecord, "无权限更新该数据或数据不存在");
    }

    private void updateAndRefresh(AiCrudConfig config,
                                  Object id,
                                  Map<String, Object> data,
                                  DynamicCrudRepository.SqlCondition condition,
                                  Map<String, Object> beforeRecord,
                                  String failureMessage) {
        String primaryKey = primaryKeyColumn(currentPrimaryKey());
        int affected = repository.updateById(config.getTableName(), primaryKey, id, data, condition);
        if (affected <= 0) {
            throw new BusinessException(failureMessage);
        }
        refreshAfterUpdate(config, id, beforeRecord);
    }

    private void refreshAfterUpdate(AiCrudConfig config, Object id, Map<String, Object> beforeRecord) {
        storedAggregateRefreshService.refreshAfterChildUpdate(config, beforeRecord,
                repository.selectById(config.getTableName(), primaryKeyColumn(currentPrimaryKey()), id, null));
    }

    private RuntimeJoinContext buildRuntimeJoinContext(AiCrudConfig config) {
        return runtimeRelationPlanner.buildRuntimeJoinContext(
                config,
                writeFieldPolicy::buildRuntimeColumnMapping,
                masterDetailEngine::preferReadableChildRelation);
    }

    private void prepareStorageWrite(Map<String, Object> data, AiCrudConfig config) {
        fieldValuePipeline.applyStructuredFieldStorageWrite(data, config);
        fieldValuePipeline.applyEncrypt(data, config.getEncryptConfig());
    }

    private void validateUniqueConstraints(AiCrudConfig config,
                                           String tableName,
                                           Map<String, Object> data,
                                           Map<String, Object> beforeRecord,
                                           Object excludeId) {
        uniquenessValidator.validate(
                config, tableName, data, beforeRecord, excludeId,
                primaryKeyColumn(currentPrimaryKey()));
    }

    private BusinessException emptyWriteFieldsException(AiCrudConfig config,
                                                        Set<String> submittedKeys,
                                                        Set<String> allowedFields) {
        String configKey = config == null ? "" : StringUtils.defaultString(config.getConfigKey());
        String tableName = config == null ? "" : StringUtils.defaultString(config.getTableName());
        long submittedBusiness = submittedKeys == null ? 0
                : submittedKeys.stream().filter(key -> !isImmutableWriteField(key)
                        && !DataAuditPayloadSupport.PAYLOAD_KEY.equals(key)
                        && !"main".equals(key)
                        && !"children".equals(key)).count();
        return new BusinessException("没有可更新的字段（对象 " + configKey + " / 表 " + tableName + "）。"
                + "请求里业务字段约 " + submittedBusiness + " 个，白名单可写字段 "
                + (allowedFields == null ? 0 : allowedFields.size()) + " 个，过滤后为空。"
                + "请检查：1) 字段已在表单设计中可见且已同步到物理表；"
                + "2) 字段未设为隐藏/禁用/只读；"
                + "3) 字段编码与模型一致；"
                + "4) 不要只提交 id 等系统字段。");
    }

    @SuppressWarnings("unchecked")
    private Object resolvePayloadId(Map<String, Object> data, LowcodePrimaryKeyStrategy primaryKey) {
        if (data == null) {
            return null;
        }
        Object idValue = firstPresent(data, primaryKeyField(primaryKey), primaryKeyColumn(primaryKey), "id");
        if (idValue != null) {
            return idValue;
        }
        Object main = data.get("main");
        if (main instanceof Map<?, ?> map) {
            return firstPresent((Map<String, Object>) map,
                    primaryKeyField(primaryKey), primaryKeyColumn(primaryKey), "id");
        }
        return null;
    }

    private Object firstPresent(Map<String, Object> data, String... keys) {
        for (String key : keys) {
            if (StringUtils.isNotBlank(key) && data.containsKey(key)) {
                return data.get(key);
            }
        }
        return null;
    }

    private void removePrimaryKeyColumns(Map<String, Object> data, LowcodePrimaryKeyStrategy primaryKey) {
        data.remove(primaryKeyField(primaryKey));
        data.remove(primaryKeyColumn(primaryKey));
        data.remove(DynamicQueryGenerator.snakeToCamel(primaryKeyColumn(primaryKey)));
        data.remove(DynamicQueryGenerator.camelToSnake(primaryKeyField(primaryKey)));
        data.remove("id");
    }

    private void putPrimaryKeyAlias(Map<String, Object> data, LowcodePrimaryKeyStrategy primaryKey, Object id) {
        if (id == null) {
            return;
        }
        data.put(primaryKeyField(primaryKey), id);
        data.put(primaryKeyColumn(primaryKey), id);
        data.put("id", id);
    }

    private boolean isPrimaryKeyAlias(String fieldName,
                                      String columnName,
                                      LowcodePrimaryKeyStrategy primaryKey) {
        String primaryField = primaryKeyField(primaryKey);
        String primaryColumn = primaryKeyColumn(primaryKey);
        return equalsFieldAlias(fieldName, primaryField)
                || equalsFieldAlias(fieldName, primaryColumn)
                || equalsFieldAlias(columnName, primaryColumn);
    }

    private boolean equalsFieldAlias(String actual, String expected) {
        if (StringUtils.isBlank(actual) || StringUtils.isBlank(expected)) {
            return false;
        }
        return actual.equals(expected)
                || actual.equals(DynamicQueryGenerator.snakeToCamel(expected))
                || actual.equals(DynamicQueryGenerator.camelToSnake(expected));
    }

    private boolean isImmutableWriteField(String key) {
        return IMMUTABLE_WRITE_FIELDS.contains(key);
    }

    private LowcodePrimaryKeyStrategy currentPrimaryKey() {
        LowcodeRuntimeDataSourceContext context = LowcodeRuntimeDataSourceContextHolder.get();
        LowcodePrimaryKeyStrategy primaryKey = context == null ? null : context.getPrimaryKey();
        if (primaryKey == null) {
            primaryKey = new LowcodePrimaryKeyStrategy();
            primaryKey.setField("id");
            primaryKey.setColumnName("id");
            primaryKey.setDataType("bigint");
            primaryKey.setAutoIncrement(true);
        }
        return primaryKey;
    }

    private String primaryKeyField(LowcodePrimaryKeyStrategy primaryKey) {
        return StringUtils.defaultIfBlank(primaryKey == null ? null : primaryKey.getField(), "id");
    }

    private String primaryKeyColumn(LowcodePrimaryKeyStrategy primaryKey) {
        return StringUtils.defaultIfBlank(primaryKey == null ? null : primaryKey.getColumnName(), "id");
    }

    private boolean primaryKeyAutoIncrement(LowcodePrimaryKeyStrategy primaryKey) {
        return primaryKey == null || primaryKey.getAutoIncrement() == null || primaryKey.getAutoIncrement();
    }
}
