package com.mdframe.forge.plugin.generator.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mdframe.forge.plugin.generator.domain.entity.AiBusinessDocumentConfig;
import com.mdframe.forge.plugin.generator.domain.entity.AiCrudConfig;
import com.mdframe.forge.plugin.generator.dto.lowcode.LowcodeFieldSchema;
import com.mdframe.forge.plugin.generator.dto.lowcode.LowcodeModelSchema;
import com.mdframe.forge.plugin.generator.service.businessapp.BusinessDocumentConfigService;
import com.mdframe.forge.plugin.generator.service.businessapp.CodeRuleService;
import com.mdframe.forge.plugin.generator.util.DynamicQueryGenerator;
import com.mdframe.forge.starter.core.exception.BusinessException;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/** Applies explicit and conventional code rules plus governed document-number generation. */
@Slf4j
final class DynamicCrudGeneratedFieldPolicy {

    private record AutoGenerationField(String fieldName,
                                       String columnName,
                                       String label,
                                       String ruleCode,
                                       String trigger,
                                       String fillPolicy,
                                       boolean enabled) {
    }

    private final DynamicCrudRepository repository;
    private final ObjectMapper objectMapper;
    private final BusinessDocumentConfigService documentConfigService;
    private final CodeRuleService codeRuleService;

    DynamicCrudGeneratedFieldPolicy(
            DynamicCrudRepository repository,
            ObjectMapper objectMapper,
            BusinessDocumentConfigService documentConfigService,
            CodeRuleService codeRuleService) {
        this.repository = repository;
        this.objectMapper = objectMapper;
        this.documentConfigService = documentConfigService;
        this.codeRuleService = codeRuleService;
    }

    void applyAutoGeneratedFields(
            AiCrudConfig config, Map<String, Object> data, Set<String> allowedFields) {
        if (config == null || data == null) {
            return;
        }
        List<AutoGenerationField> autoFields = collectAutoGenerationFields(config);
        if (autoFields.isEmpty()) {
            applyConventionalCodeRuleFields(config, data, allowedFields);
            return;
        }
        Map<String, Object> mainPayload = extractMainPayload(data);
        for (AutoGenerationField field : autoFields) {
            if (!field.enabled() || !"ON_CREATE".equalsIgnoreCase(field.trigger())) {
                continue;
            }
            Set<String> writableAliases = resolveDocumentNoWritableAliases(
                    config, StringUtils.firstNonBlank(field.fieldName(), field.columnName()));
            if (writableAliases.isEmpty()) {
                log.warn("[DynamicCrudGeneratedFieldPolicy] 自动编号字段未匹配到业务表列, configKey={}, field={}",
                        config.getConfigKey(), field.fieldName());
                continue;
            }
            if (allowedFields != null) {
                allowedFields.addAll(writableAliases);
            }
            if ("EMPTY_ONLY".equalsIgnoreCase(field.fillPolicy())
                    && hasFieldValue(mainPayload, writableAliases)) {
                continue;
            }
            String generatedCode = codeRuleService.generate(
                    field.ruleCode(), buildCodeRuleContext(config, mainPayload, field));
            if (StringUtils.isBlank(generatedCode)) {
                continue;
            }
            writableAliases.forEach(alias -> mainPayload.put(alias, generatedCode));
        }
        applyConventionalCodeRuleFields(config, data, allowedFields);
    }

    void applyDocumentNoIfNeeded(
            AiCrudConfig config, Map<String, Object> data, Set<String> allowedFields) {
        if (config == null || data == null) {
            return;
        }
        AiBusinessDocumentConfig documentConfig = resolveEnabledDocumentConfig(config);
        if (documentConfig == null) {
            return;
        }
        String documentNoField = documentConfigService.resolveDocumentNoField(documentConfig, config);
        if (StringUtils.isBlank(documentNoField)) {
            return;
        }
        Set<String> writableAliases = resolveDocumentNoWritableAliases(config, documentNoField);
        if (writableAliases.isEmpty()) {
            log.warn("[DynamicCrudGeneratedFieldPolicy] 单据编号字段未匹配到业务表列, configKey={}, documentNoField={}",
                    config.getConfigKey(), documentNoField);
            return;
        }
        if (allowedFields != null) {
            allowedFields.addAll(writableAliases);
        }
        Map<String, Object> mainPayload = extractMainPayload(data);
        if (hasAutoGenerationConfig(config, documentNoField)) {
            return;
        }
        String documentNo = documentConfigService.generateDocumentNo(documentConfig, mainPayload);
        if (StringUtils.isBlank(documentNo)) {
            return;
        }
        writableAliases.forEach(alias -> mainPayload.put(alias, documentNo));
    }

    private List<AutoGenerationField> collectAutoGenerationFields(AiCrudConfig config) {
        if (config == null) {
            return List.of();
        }
        Map<String, AutoGenerationField> fields = new LinkedHashMap<>();
        LowcodeModelSchema modelSchema = parseModelSchema(config);
        if (modelSchema != null && modelSchema.getFields() != null) {
            for (LowcodeFieldSchema field : modelSchema.getFields()) {
                AutoGenerationField autoField = buildAutoGenerationField(
                        field == null ? null : field.getField(),
                        field == null ? null : field.getColumnName(),
                        field == null ? null : field.getLabel(),
                        firstMap(
                                field == null || field.getBasicProps() == null
                                        ? null : field.getBasicProps().get("generation"),
                                field == null || field.getAdvancedProps() == null
                                        ? null : field.getAdvancedProps().get("generation")));
                putAutoGenerationField(fields, autoField);
            }
        }
        for (Map<String, Object> editField : readEditSchemaFields(config)) {
            Map<String, Object> props = mapFrom(editField.get("props"));
            Map<String, Object> advancedProps = mapFrom(editField.get("advancedProps"));
            AutoGenerationField autoField = buildAutoGenerationField(
                    text(editField.get("field")),
                    StringUtils.firstNonBlank(
                            text(editField.get("columnName")), text(editField.get("fieldCode"))),
                    StringUtils.firstNonBlank(text(editField.get("label")), text(editField.get("title"))),
                    firstMap(props.get("generation"), editField.get("generation"),
                            advancedProps.get("generation")));
            putAutoGenerationField(fields, autoField);
        }
        return new ArrayList<>(fields.values());
    }

    private void putAutoGenerationField(
            Map<String, AutoGenerationField> fields, AutoGenerationField field) {
        if (field == null || !field.enabled() || StringUtils.isBlank(field.ruleCode())) {
            return;
        }
        String key = StringUtils.firstNonBlank(field.fieldName(), field.columnName());
        if (StringUtils.isNotBlank(key)) {
            fields.putIfAbsent(key, field);
        }
    }

    private AutoGenerationField buildAutoGenerationField(
            String fieldName, String columnName, String label, Map<String, Object> generation) {
        if (generation == null || generation.isEmpty() || !readBoolean(generation.get("enabled"), false)) {
            return null;
        }
        String ruleCode = StringUtils.firstNonBlank(
                text(generation.get("ruleCode")),
                text(generation.get("codeRuleCode")),
                text(generation.get("generatorCode")));
        if (StringUtils.isBlank(ruleCode)) {
            return null;
        }
        String mode = StringUtils.defaultIfBlank(
                StringUtils.firstNonBlank(text(generation.get("mode")), text(generation.get("type"))),
                "CODE_RULE");
        if (!"CODE_RULE".equalsIgnoreCase(mode) && !"AUTO_CODE".equalsIgnoreCase(mode)) {
            return null;
        }
        return new AutoGenerationField(
                StringUtils.trimToNull(fieldName),
                StringUtils.trimToNull(columnName),
                StringUtils.trimToNull(label),
                ruleCode.trim(),
                StringUtils.defaultIfBlank(text(generation.get("trigger")), "ON_CREATE").trim(),
                StringUtils.defaultIfBlank(text(generation.get("fillPolicy")), "EMPTY_ONLY").trim(),
                true);
    }

    private void applyConventionalCodeRuleFields(
            AiCrudConfig config, Map<String, Object> data, Set<String> allowedFields) {
        List<AutoGenerationField> fields = collectConventionalCodeRuleFields(config);
        if (fields.isEmpty()) {
            return;
        }
        Map<String, Object> mainPayload = extractMainPayload(data);
        for (AutoGenerationField field : fields) {
            Set<String> writableAliases = resolveDocumentNoWritableAliases(
                    config, StringUtils.firstNonBlank(field.fieldName(), field.columnName()));
            if (writableAliases.isEmpty() || hasFieldValue(mainPayload, writableAliases)) {
                continue;
            }
            String generatedCode = tryGenerateConventionalCode(config, mainPayload, field);
            if (StringUtils.isBlank(generatedCode)) {
                continue;
            }
            if (allowedFields != null) {
                allowedFields.addAll(writableAliases);
            }
            writableAliases.forEach(alias -> mainPayload.put(alias, generatedCode));
        }
    }

    private List<AutoGenerationField> collectConventionalCodeRuleFields(AiCrudConfig config) {
        if (config == null) {
            return List.of();
        }
        Map<String, AutoGenerationField> fields = new LinkedHashMap<>();
        Set<String> generationConfiguredAliases = new LinkedHashSet<>();
        LowcodeModelSchema modelSchema = parseModelSchema(config);
        if (modelSchema != null && modelSchema.getFields() != null) {
            for (LowcodeFieldSchema field : modelSchema.getFields()) {
                if (field != null && hasGenerationConfig(field.getBasicProps(), field.getAdvancedProps())) {
                    addFieldAliases(generationConfiguredAliases, field.getField(), field.getColumnName());
                    continue;
                }
                putAutoGenerationField(fields, buildConventionalCodeRuleField(field));
            }
        }
        appendConventionalEditFields(config, fields, generationConfiguredAliases);
        return new ArrayList<>(fields.values());
    }

    private void appendConventionalEditFields(
            AiCrudConfig config,
            Map<String, AutoGenerationField> fields,
            Set<String> generationConfiguredAliases) {
        for (Map<String, Object> editField : readEditSchemaFields(config)) {
            String fieldName = text(editField.get("field"));
            String columnName = StringUtils.firstNonBlank(
                    text(editField.get("columnName")), text(editField.get("fieldCode")));
            Map<String, Object> props = mapFrom(editField.get("props"));
            Map<String, Object> advancedProps = mapFrom(editField.get("advancedProps"));
            if (!firstMap(props.get("generation"), editField.get("generation"),
                    advancedProps.get("generation")).isEmpty()) {
                addFieldAliases(generationConfiguredAliases, fieldName, columnName);
                continue;
            }
            if (matchesAnyAlias(fieldName, generationConfiguredAliases)
                    || matchesAnyAlias(columnName, generationConfiguredAliases)) {
                continue;
            }
            putAutoGenerationField(fields, buildConventionalCodeRuleField(
                    fieldName,
                    columnName,
                    StringUtils.firstNonBlank(text(editField.get("label")), text(editField.get("title"))),
                    props,
                    advancedProps));
        }
    }

    private AutoGenerationField buildConventionalCodeRuleField(LowcodeFieldSchema field) {
        if (field == null || Boolean.TRUE.equals(field.getSystemField())
                || "DISABLED".equalsIgnoreCase(StringUtils.defaultString(field.getFieldStatus()))
                || "HIDDEN".equalsIgnoreCase(StringUtils.defaultString(field.getFieldStatus()))) {
            return null;
        }
        return buildConventionalCodeRuleField(
                field.getField(), field.getColumnName(), field.getLabel(),
                field.getBasicProps(), field.getAdvancedProps());
    }

    private AutoGenerationField buildConventionalCodeRuleField(
            String fieldName,
            String columnName,
            String label,
            Map<String, Object> basicProps,
            Map<String, Object> advancedProps) {
        if (hasGenerationConfig(basicProps, advancedProps)
                || !isConventionalCodeField(fieldName, columnName, label)) {
            return null;
        }
        String ruleCode = StringUtils.firstNonBlank(
                columnName, DynamicQueryGenerator.camelToSnake(fieldName));
        return StringUtils.isBlank(ruleCode) ? null : new AutoGenerationField(
                StringUtils.trimToNull(fieldName),
                StringUtils.trimToNull(columnName),
                StringUtils.trimToNull(label),
                ruleCode.trim(), "ON_CREATE", "EMPTY_ONLY", true);
    }

    private boolean isConventionalCodeField(String fieldName, String columnName, String label) {
        String fieldLower = StringUtils.defaultString(fieldName).toLowerCase(Locale.ROOT);
        String columnLower = StringUtils.defaultString(columnName).toLowerCase(Locale.ROOT);
        return fieldLower.endsWith("code")
                || fieldLower.endsWith("no")
                || columnLower.endsWith("_code")
                || columnLower.endsWith("_no")
                || StringUtils.containsAny(StringUtils.defaultString(label), "编号", "单号");
    }

    private String tryGenerateConventionalCode(
            AiCrudConfig config, Map<String, Object> mainPayload, AutoGenerationField field) {
        try {
            return codeRuleService.generate(
                    field.ruleCode(), buildCodeRuleContext(config, mainPayload, field));
        } catch (BusinessException e) {
            log.debug("[DynamicCrudGeneratedFieldPolicy] 未使用约定编码规则生成字段, "
                            + "configKey={}, field={}, ruleCode={}, reason={}",
                    config.getConfigKey(), field.fieldName(), field.ruleCode(), e.getMessage());
            return null;
        }
    }

    private boolean hasAutoGenerationConfig(AiCrudConfig config, String fieldName) {
        if (StringUtils.isBlank(fieldName)) {
            return false;
        }
        Set<String> requestedAliases = documentNoAliasSet(fieldName);
        return collectAutoGenerationFields(config).stream()
                .anyMatch(field -> matchesAnyAlias(field.fieldName(), requestedAliases)
                        || matchesAnyAlias(field.columnName(), requestedAliases));
    }

    private AiBusinessDocumentConfig resolveEnabledDocumentConfig(AiCrudConfig config) {
        AiBusinessDocumentConfig documentConfig = documentConfigService.selectEnabledByConfigKey(
                config.getTenantId(), config.getConfigKey());
        if (documentConfig == null && StringUtils.isNotBlank(config.getObjectCode())) {
            documentConfig = documentConfigService.selectEnabledByObjectCode(
                    config.getTenantId(), config.getObjectCode());
        }
        return documentConfig;
    }

    private Set<String> resolveDocumentNoWritableAliases(AiCrudConfig config, String documentNoField) {
        Set<String> aliases = new LinkedHashSet<>();
        if (config == null || StringUtils.isBlank(config.getTableName())
                || StringUtils.isBlank(documentNoField)) {
            return aliases;
        }
        Map<String, String> columnMapping = buildRuntimeColumnMapping(config, config.getTableName());
        addDocumentNoAliasIfWritable(aliases, documentNoField, columnMapping);
        LowcodeModelSchema modelSchema = parseModelSchema(config);
        if (modelSchema == null || modelSchema.getFields() == null) {
            return aliases;
        }
        Set<String> requestedAliases = documentNoAliasSet(documentNoField);
        for (LowcodeFieldSchema field : modelSchema.getFields()) {
            if (field != null && (matchesAnyAlias(field.getField(), requestedAliases)
                    || matchesAnyAlias(field.getColumnName(), requestedAliases))) {
                addDocumentNoAliasIfWritable(aliases, field.getField(), columnMapping);
                addDocumentNoAliasIfWritable(aliases, field.getColumnName(), columnMapping);
            }
        }
        return aliases;
    }

    private Map<String, String> buildRuntimeColumnMapping(AiCrudConfig config, String tableName) {
        Map<String, String> result = new LinkedHashMap<>(repository.getColumnMapping(tableName));
        LowcodeModelSchema modelSchema = parseModelSchema(config);
        if (config == null || !StringUtils.equals(tableName, config.getTableName())
                || modelSchema == null || modelSchema.getFields() == null) {
            return result;
        }
        for (LowcodeFieldSchema field : modelSchema.getFields()) {
            if (field == null) {
                continue;
            }
            String columnName = StringUtils.trimToNull(StringUtils.defaultIfBlank(
                    field.getColumnName(), DynamicQueryGenerator.camelToSnake(field.getField())));
            if (columnName == null) {
                continue;
            }
            String normalizedColumn = columnName.toLowerCase(Locale.ROOT);
            putColumnAlias(result, field.getField(), normalizedColumn);
            putColumnAlias(result, field.getColumnName(), normalizedColumn);
        }
        return result;
    }

    private void putColumnAlias(Map<String, String> mapping, String alias, String columnName) {
        if (StringUtils.isBlank(alias) || StringUtils.isBlank(columnName)) {
            return;
        }
        mapping.put(alias, columnName);
        mapping.put(DynamicQueryGenerator.snakeToCamel(alias), columnName);
        mapping.put(DynamicQueryGenerator.camelToSnake(alias), columnName);
    }

    private Map<String, Object> buildCodeRuleContext(
            AiCrudConfig config, Map<String, Object> recordData, AutoGenerationField field) {
        Map<String, Object> fields = new LinkedHashMap<>();
        if (recordData != null) {
            fields.putAll(recordData);
        }
        fields.put("suiteCode", StringUtils.defaultIfBlank(config.getDomainCode(), ""));
        fields.put("objectCode", StringUtils.defaultIfBlank(config.getObjectCode(), ""));
        fields.put("configKey", StringUtils.defaultIfBlank(config.getConfigKey(), ""));
        fields.put("fieldCode", StringUtils.defaultIfBlank(field.fieldName(), field.columnName()));
        fields.put("fieldName", StringUtils.defaultIfBlank(field.label(), field.fieldName()));
        return new LinkedHashMap<>(Map.of("fields", fields));
    }

    private List<Map<String, Object>> readEditSchemaFields(AiCrudConfig config) {
        if (config == null || StringUtils.isBlank(config.getEditSchema())) {
            return List.of();
        }
        try {
            Object schema = objectMapper.readValue(config.getEditSchema(), new TypeReference<Object>() { });
            List<Map<String, Object>> result = new ArrayList<>();
            collectEditSchemaFields(schema, result);
            return result;
        } catch (Exception e) {
            log.warn("[DynamicCrudGeneratedFieldPolicy] 解析 editSchema 生成规则失败, configKey={}",
                    config.getConfigKey(), e);
            return List.of();
        }
    }

    @SuppressWarnings("unchecked")
    private void collectEditSchemaFields(Object node, List<Map<String, Object>> result) {
        if (node instanceof List<?> list) {
            list.forEach(item -> collectEditSchemaFields(item, result));
            return;
        }
        if (!(node instanceof Map<?, ?> rawMap)) {
            return;
        }
        Map<String, Object> map = (Map<String, Object>) rawMap;
        if (StringUtils.isNotBlank(text(map.get("field")))) {
            result.add(map);
        }
        collectEditSchemaFields(map.get("children"), result);
        collectEditSchemaFields(map.get("items"), result);
        collectEditSchemaFields(map.get("components"), result);
    }

    private LowcodeModelSchema parseModelSchema(AiCrudConfig config) {
        if (config == null || StringUtils.isBlank(config.getModelSchema())) {
            return null;
        }
        try {
            return objectMapper.readValue(config.getModelSchema(), LowcodeModelSchema.class);
        } catch (Exception e) {
            log.warn("[DynamicCrudGeneratedFieldPolicy] 解析 modelSchema 失败, configKey={}",
                    config.getConfigKey(), e);
            return null;
        }
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> extractMainPayload(Map<String, Object> data) {
        return data != null && data.get("main") instanceof Map<?, ?> main
                ? (Map<String, Object>) main : data == null ? Map.of() : data;
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> mapFrom(Object value) {
        return value instanceof Map<?, ?> map ? (Map<String, Object>) map : Map.of();
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> firstMap(Object... values) {
        if (values != null) {
            for (Object value : values) {
                if (value instanceof Map<?, ?> map && !map.isEmpty()) {
                    return (Map<String, Object>) map;
                }
            }
        }
        return Map.of();
    }

    private boolean readBoolean(Object value, boolean defaultValue) {
        if (value == null) {
            return defaultValue;
        }
        if (value instanceof Boolean bool) {
            return bool;
        }
        if (value instanceof Number number) {
            return number.intValue() != 0;
        }
        String textValue = String.valueOf(value).trim();
        return StringUtils.isBlank(textValue) ? defaultValue
                : "true".equalsIgnoreCase(textValue)
                || "1".equals(textValue)
                || "yes".equalsIgnoreCase(textValue)
                || "Y".equalsIgnoreCase(textValue);
    }

    private boolean hasFieldValue(Map<String, Object> data, Set<String> aliases) {
        if (data == null || aliases == null || aliases.isEmpty()) {
            return false;
        }
        return aliases.stream().map(data::get).anyMatch(value -> value != null
                && (!(value instanceof String textValue) || StringUtils.isNotBlank(textValue)));
    }

    private boolean hasGenerationConfig(
            Map<String, Object> basicProps, Map<String, Object> advancedProps) {
        return !firstMap(
                basicProps == null ? null : basicProps.get("generation"),
                advancedProps == null ? null : advancedProps.get("generation")).isEmpty();
    }

    private void addFieldAliases(Set<String> aliases, String fieldName, String columnName) {
        aliases.addAll(documentNoAliasSet(fieldName));
        aliases.addAll(documentNoAliasSet(columnName));
    }

    private Set<String> documentNoAliasSet(String field) {
        Set<String> aliases = new LinkedHashSet<>();
        if (StringUtils.isNotBlank(field)) {
            aliases.add(field);
            aliases.add(DynamicQueryGenerator.snakeToCamel(field));
            aliases.add(DynamicQueryGenerator.camelToSnake(field));
        }
        return aliases;
    }

    private boolean matchesAnyAlias(String field, Set<String> aliases) {
        return StringUtils.isNotBlank(field) && aliases != null && !aliases.isEmpty()
                && (aliases.contains(field)
                || aliases.contains(DynamicQueryGenerator.snakeToCamel(field))
                || aliases.contains(DynamicQueryGenerator.camelToSnake(field)));
    }

    private void addDocumentNoAliasIfWritable(
            Set<String> aliases, String field, Map<String, String> columnMapping) {
        if (StringUtils.isBlank(field) || columnMapping == null || columnMapping.isEmpty()) {
            return;
        }
        for (String alias : documentNoAliasSet(field)) {
            if (columnMapping.containsKey(alias)) {
                aliases.add(alias);
            }
        }
    }

    private String text(Object value) {
        return value == null ? null : String.valueOf(value);
    }
}
