-- Forge 原生打印持久化。仅新增结构；不操作已有业务数据。
-- 回滚：停用模块并保留模板/版本/审计；禁止自动 DROP。默认绑定需应用级事务锁，见 SDD。

CREATE TABLE IF NOT EXISTS sys_print_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL COMMENT '应用 ID',
    template_code VARCHAR(80) NOT NULL COMMENT '应用内模板编码',
    template_name VARCHAR(100) NOT NULL COMMENT '模板名称',
    source_type VARCHAR(20) NOT NULL COMMENT 'LOWCODE/CODE',
    source_key VARCHAR(191) NOT NULL COMMENT '服务端规范化来源',
    page_id BIGINT NULL COMMENT '低代码页面',
    form_key VARCHAR(128) NULL COMMENT '代码表单标识',
    object_code VARCHAR(100) NOT NULL COMMENT '业务对象编码',
    draft_schema MEDIUMTEXT NOT NULL COMMENT '已校验的协议草稿',
    draft_revision BIGINT NOT NULL DEFAULT 1 COMMENT '并发修订号',
    design_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '设计状态',
    published_version_id BIGINT NULL COMMENT '当前发布版本',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '启停',
    del_flag BIGINT NOT NULL DEFAULT 0 COMMENT '删除墓碑：有效为 0，删除写主键',
    create_by BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_dept BIGINT NULL,
    update_by BIGINT NOT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_print_template_code (tenant_id, application_id, template_code, del_flag),
    KEY idx_print_template_source (tenant_id, application_id, source_key, status, del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_print_template_version (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL COMMENT '模板 ID',
    version_no INT NOT NULL COMMENT '跨历史永久唯一版本号',
    schema_version INT NOT NULL COMMENT '协议版本',
    schema_json MEDIUMTEXT NOT NULL COMMENT '不可变规范化协议',
    schema_hash CHAR(64) NOT NULL COMMENT '规范化协议 SHA-256',
    resource_manifest TEXT NOT NULL COMMENT '受控文件标识清单，不含签名 URL',
    publish_time DATETIME NOT NULL COMMENT '发布时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除，不释放版本号',
    create_by BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_dept BIGINT NULL,
    update_by BIGINT NOT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_print_version_no (tenant_id, template_id, version_no),
    KEY idx_print_version_hash (tenant_id, template_id, schema_hash, del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_print_binding (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL COMMENT '应用 ID',
    source_type VARCHAR(20) NOT NULL COMMENT '来源类型',
    source_key VARCHAR(191) NOT NULL COMMENT '服务端规范化来源',
    page_id BIGINT NULL COMMENT '低代码页面',
    form_key VARCHAR(128) NULL COMMENT '代码表单标识',
    object_code VARCHAR(100) NOT NULL COMMENT '对象编码',
    template_id BIGINT NOT NULL COMMENT '模板 ID',
    scene VARCHAR(30) NOT NULL COMMENT '使用场景',
    is_default TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认，同应用锁内维护',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '启停',
    binding_revision BIGINT NOT NULL DEFAULT 1 COMMENT '绑定并发修订号',
    del_flag BIGINT NOT NULL DEFAULT 0 COMMENT '删除墓碑',
    create_by BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_dept BIGINT NULL,
    update_by BIGINT NOT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_print_binding_source (tenant_id, application_id, source_key, template_id, scene, del_flag),
    KEY idx_print_binding_template (tenant_id, template_id, del_flag),
    KEY idx_print_binding_default (tenant_id, application_id, source_key, scene, is_default, status, del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_print_execution (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL COMMENT '应用 ID',
    application_version_id BIGINT NULL COMMENT '应用发布版本',
    template_id BIGINT NOT NULL COMMENT '模板 ID',
    template_version_id BIGINT NOT NULL COMMENT '实际打印版本',
    source_key VARCHAR(191) NOT NULL COMMENT '规范化来源',
    object_code VARCHAR(100) NOT NULL COMMENT '对象编码',
    record_id VARCHAR(128) NOT NULL COMMENT '记录 ID',
    scene VARCHAR(30) NOT NULL COMMENT '运行场景',
    task_id VARCHAR(128) NULL COMMENT '流程任务 ID',
    process_instance_id VARCHAR(128) NULL COMMENT '流程实例 ID',
    process_run_id BIGINT NULL COMMENT '业务流程运行 ID',
    actor BIGINT NOT NULL COMMENT '服务端登录操作者',
    data_mode VARCHAR(20) NOT NULL DEFAULT 'CURRENT' COMMENT '数据模式',
    generated_at DATETIME NOT NULL COMMENT '数据生成时刻',
    result VARCHAR(30) NOT NULL DEFAULT 'PREPARED' COMMENT 'PREPARED/DIALOG_OPENED/FAILED，不代表物理出纸',
    error_code VARCHAR(80) NULL COMMENT '受限错误码，不存消息正文',
    page_count INT NULL COMMENT '准备后页数，最大 50',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    create_by BIGINT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_dept BIGINT NULL,
    update_by BIGINT NOT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_print_execution_actor (tenant_id, actor, generated_at, del_flag),
    KEY idx_print_execution_version (tenant_id, template_version_id, del_flag),
    KEY idx_print_execution_record (tenant_id, application_id, object_code, record_id, del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
